/**
 * Watermark utility for Excel files
 * Adds 'nurasyid' watermark to generated Excel files
 */

const WATERMARK_TEXT = 'nurasyid';

export const addWatermark = (worksheet) => {
  worksheet.headerFooter.oddHeader = `&C&GnurasyidWatermark.png`;
  worksheet.headerFooter.oddFooter = `&C&D | watermarked by nurasyid`;
  
  worksheet.background = {
    type: 'pattern',
    pattern: 'lightGrid',
    fgColor: { argb: 'FFE0E0E0' },
    bgColor: { argb: 'FFFFFFFF' }
  };
};

export const addWatermarkNote = (worksheet) => {
  const firstCell = worksheet.getCell('A1');
  if (firstCell) {
    firstCell.note = {
      texts: [{
        font: { size: 10, color: { type: 'pattern', pattern: 'lightGray' } },
        rich: true,
        text: `File generated and watermarked by nurasyid - Excel Chatbot AI`
      }],
      margins: { insetmode: 'custom', l: 100, t: 100, r: 100, b: 100 },
      protection: { locked: true, lockText: true }
    };
  }
};

export const getWatermarkMetadata = () => {
  return {
    creator: 'nurasyid Excel Chatbot AI',
    createdAt: new Date(),
    watermark: WATERMARK_TEXT,
    company: 'nurasyid',
    subject: 'Excel file generated by AI Chatbot'
  };
};

export default { addWatermark, addWatermarkNote, getWatermarkMetadata, WATERMARK_TEXT };
